server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,fserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,=server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,qserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,userver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,(server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,'server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,fserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,'server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,)server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,;server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,qserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,=server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,qserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,userver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,(server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,'server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,mserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,qserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,'server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,)server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,;server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,qserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,userver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,(server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,'server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,dserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,vserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,'server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,)server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,fserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,gserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,(server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,)server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,;server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,fserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,gserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,=server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,{server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,userver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,:server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,vserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Dserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Bserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,_server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Userver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,wserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,dserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,:server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,vserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Dserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Bserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,_server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Wserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Dserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,|server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,|server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,'server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,hserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,'server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,dserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,bserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,:server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,vserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Dserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Bserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,_server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Dserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Bserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,:server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,{server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,yserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,:server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,fserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,userver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,vserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,fserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,:server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,userver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,}server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,}server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,;server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,yserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,fserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,userver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,yserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,qserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,(server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,)server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,{server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,yserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,{server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,gserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,(server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,'server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,gserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,'server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,fserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,gserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,vserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,fserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,gserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,dserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,bserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,)server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,;server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,=server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,wserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,qserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,(server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,fserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,gserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,)server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,;server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,gserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,(server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,'server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,dserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,'server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,)server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,;server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,qserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,userver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,yserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,=server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,fserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,dserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Fserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,yserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,(server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,'server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,/server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Qserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,/server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,dserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,mserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,/server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,dserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,bserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,_server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Fserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,hserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,_server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,hserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,dserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,qserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,'server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,'server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,userver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,fserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,8server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,'server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,)server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,;server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,wserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,qserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,userver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,(server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,)server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,bserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,hserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,(server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,qserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,userver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,yserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,)server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,;server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,gserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,(server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,'server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,dserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,dserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,userver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,userver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,fserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,userver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,yserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,dserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,'server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,)server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,;server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,xserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,(server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,0server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,)server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,;server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,}server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,hserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,(server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,)server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,{server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,(server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,'server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,yserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,nserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,gserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Qserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,:server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,'server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,)server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,;server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,rserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,oserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,cserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,.server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,eserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,xserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,iserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,tserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,(server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,1server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,)server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,;server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433, server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,}server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,}server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,aserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,pserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,yserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,Sserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,qserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,lserver: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,(server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,)server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,;server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
server: process.env.DB_SERVER || 'localhost',
    port: parseInt(process.env.DB_PORT) || 1433,
