CREATE TABLE [dbo].[CatalogoPuestos] (

[PuestoId] int IDENTITY(1,1) NOT NULL,
[CodRef] nvarchar(20) NULL,
[Nombre] nvarchar(200) NOT NULL,
[Activo] bit DEFAULT ((1)) NOT NULL,
CONSTRAINT [PK__Catalogo__F7F6C6045872112F] PRIMARY KEY CLUSTERED ([PuestoId] ASC) WITH (PAD_INDEX = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
CONSTRAINT [UQ__Catalogo__84823DEF6B0844E9] UNIQUE NONCLUSTERED ([CodRef] ASC) WITH (PAD_INDEX = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
