CREATE TABLE [dbo].[UsuariosRoles] (

[UsuarioId] int NOT NULL,
[RoleId] int NOT NULL,
[EsPrincipal] bit DEFAULT ((0)) NOT NULL,
CONSTRAINT [PK__Usuarios__93924B593806F1F0] PRIMARY KEY CLUSTERED ([UsuarioId] ASC, [RoleId] ASC) WITH (PAD_INDEX = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
