CREATE TABLE [dbo].[Roles] (

[RoleId] int IDENTITY(1,1) NOT NULL,
[NombreRol] nvarchar(100) NOT NULL,
[Descripcion] nvarchar(510) NULL,
[FechaCreacion] datetime DEFAULT (getdate()) NULL,
CONSTRAINT [PK__Roles__8AFACE1A619C55FA] PRIMARY KEY CLUSTERED ([RoleId] ASC) WITH (PAD_INDEX = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
CONSTRAINT [UQ__Roles__4F0B537F43A3B8D4] UNIQUE NONCLUSTERED ([NombreRol] ASC) WITH (PAD_INDEX = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
