CREATE TABLE [dbo].[CatalogoGruposNomina] (

[GrupoNominaId] int IDENTITY(1,1) NOT NULL,
[CodRef] nvarchar(20) NULL,
[Nombre] nvarchar(200) NOT NULL,
[Abreviatura] nvarchar(20) NULL,
[Activo] bit DEFAULT ((1)) NOT NULL,
[Periodo] varchar(10) NULL,
CONSTRAINT [PK__Catalogo__21FBC54587866023] PRIMARY KEY CLUSTERED ([GrupoNominaId] ASC) WITH (PAD_INDEX = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
CONSTRAINT [UQ__Catalogo__84823DEF9B46BAE2] UNIQUE NONCLUSTERED ([CodRef] ASC) WITH (PAD_INDEX = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
