CREATE TABLE [dbo].[JON] (

[ID] int IDENTITY(1,1) NOT NULL,
[JSON] varchar NULL,
CONSTRAINT [PK__JON__3214EC27B952011D] PRIMARY KEY CLUSTERED ([ID] ASC) WITH (PAD_INDEX = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
