CREATE TABLE [dbo].[CatalogoDepartamentos] (

[DepartamentoId] int IDENTITY(1,1) NOT NULL,
[CodRef] nvarchar(20) NULL,
[Nombre] nvarchar(200) NOT NULL,
[Abreviatura] nvarchar(20) NULL,
[Activo] bit DEFAULT ((1)) NOT NULL,
CONSTRAINT [PK__Catalogo__66BB0E3E7076A78A] PRIMARY KEY CLUSTERED ([DepartamentoId] ASC) WITH (PAD_INDEX = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
CONSTRAINT [UQ__Catalogo__84823DEFB2F98238] UNIQUE NONCLUSTERED ([CodRef] ASC) WITH (PAD_INDEX = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
