CREATE TABLE [dbo].[ConfiguracionSistema] (

[ConfigId] int IDENTITY(1,1) NOT NULL,
[ConfigKey] nvarchar(100) NOT NULL,
[ConfigValue] nvarchar(100) NOT NULL,
[Descripcion] nvarchar(510) NULL,
CONSTRAINT [PK__Configur__C3BC335C280099B3] PRIMARY KEY CLUSTERED ([ConfigId] ASC) WITH (PAD_INDEX = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
CONSTRAINT [UQ__Configur__4A306784E5D2F2AC] UNIQUE NONCLUSTERED ([ConfigKey] ASC) WITH (PAD_INDEX = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
